### ISSUE TITLE
Telegraf throws 404 not found

### ISSUE THREAD

**Issue by doener1337** [fpfuetsch/Spritpreise#9]
Hi, i tried using your script. For some reason, telegram throws a 404

spritpreise    | (node:1) UnhandledPromiseRejectionWarning: Error: 404: Not Found
spritpreise    |     at buildConfig.then.then.then.then (/usr/src/app/node_modules/telegraf/core/network/client.js:281:17)
spritpreise    |     at process._tickCallback (internal/process/next_tick.js:68:7)
spritpreise    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
spritpreise    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fpfuetsch** [comment]
Hey, which commands are you exactly running to achieve this error?

**Comment by doener1337** [comment]
```
version: '3'

services:
  spritpreise:
    image: spritpreise:1.0.0
    container_name: spritpreise
    restart: always
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "3005:80"
    environment:
      - API_KEY="mypersonal spritpreise api key"
      - DB_URL=mongodb://db:27017
      - SERVER_PORT=3005
      - TELEGRAM_TOKEN="here i used my telegram bot token"
      - WEBHOOK_HOST=mydyndns.ddnss.de
      - UPDATE_CYCLE=10
      - SEARCH_RADIUS=20
  db:
    image: webhippie/mongodb
    restart: always
    volumes:
      - db:/var/lib/mongodb
      - db-backup:/var/lib/backup

volumes:
  db:
  db-backup:
```

So the container installed with these commands but i keep receiving the error shown in my previous post.
Thank you in advance.
